name: Run teste API
on: [push]

jobs:
  api-test:  # Renomeei este job para "api-test"
    runs-on: ubuntu-20.04  # Corrigido "ubunto-20.04" para "ubuntu-20.04"
    name: On Push - API test  # Adicionado "name" corretamente

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@3
        with:
          python-version: "3.10"

          
        
