name: Run teste API
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04  # Corrigido "ubunto-20.04" para "ubuntu-20.04"
    name: On Push - API test  # Adicionado "name" corretamente

    steps:
      - name: Ola Testes  # Adicionado um nome para o passo
        run: echo "Ola Testes"
