name: Run teste API
on: [push]

jobs:
  api-test:
  test:
    runs-on: ubuntu-20.04  # Corrigido "ubunto-20.04" para "ubuntu-20.04"
    name: On Push - API test  # Adicionado "name" corretamente

    steps:
      - name: Checkout
        user: actions/checkout@v3